homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret mylatitude 
  longitude: !secret mylongtitude
  # Impacts weather/sunrise data (altitude above sea level in meters not feet)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
 
  # Customization file
  customize: !include customize.yaml

  # Enables the frontend
frontend: 
     themes: !include amoled.yaml
 
  # Saves data to MariaDB
recorder: !include recorder.yaml

# Sensor Include File
sensor: !include sensors.yaml

# input boolean include
input_boolean: !include boolean.yaml

# Lights Include File
light: !include lights.yaml

# Switch Include File
switch: !include switches.yaml

# Locks Include File
lock: !include locks.yaml

# Binary Sensor Include
binary_sensor: !include binary_sensor.yaml
        
# Cloud Include for Google Assistant
cloud: !include cloud.yaml

# Groups of Devices
group: !include groups.yaml

# HA Automations - Not used I use node-red
automation: !include automations.yaml

# Scripts - Also not used (yet)
script: !include scripts.yaml

#system_health:

# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:
  
zone 1:
  name: Home
  latitude: !secret mylatitude
  longitude: !secret mylongtitude 
  icon: mdi:home
  radius: 500

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

#notify:
#  - name: "slack_notifier"
#    platform: slack
#    api_key: !secret slack
#    default_channel: '#home-assistant'

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# SSL configuration
http:
  base_url: !secret my_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_private_key

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key
    latitude: !secret mylatitude 
    longitude: !secret mylongtitude
    
mqtt:
    port: 1883
    broker: !secret mqtt_ip 
    username: hass
    password: !secret mqtt_password
    discovery: true
    client_id: homeassistantdocker
    discovery_prefix: homeseer

# Nest Configuration
nest:
  binary_sensors:
    monitored_conditions:
      - 'away'
      - 'has_leaf'
      - 'fan'

  client_id: !secret nest_id
  client_secret: !secret nest_secret

device_tracker:
    
cover:
  - platform: mqtt
    name: "Garage Door"
    command_topic: "homeseer/Garage/Garage_Door/Control"
    state_topic: "homeseer/Garage/Door/Status"
    payload_open: "On"
    payload_close: "On"
    payload_stop: "On"
    state_open: "0"
    state_closed: "255"
    optimistic: false
    #value_template: '{{ value.x }}'

# Text to speech
tts:
  - platform: google_translate

#google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_secret
   
ring:
  username: !secret ring_username
  password: !secret ring_password 

# Example configuration.yaml entry
#media_player:
#  - platform: spotify
#    client_id: !secret spotify_clientid
#    client_secret: !secret spotify_secret

#rest_command:
#  do_backup:
#    url: !secret backup_url
#    method: GET
#    verify_ssl: false
